spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5535/loans
    username: user
    password: user
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
  #  To connect to the Config Server
  application:
    name: loans
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:9099/
server:
  port: 8181
