apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-db
  labels:
    app: accounts-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-db
  template:
    metadata:
      labels:
        app: accounts-db
    spec:
      containers:
        - name: accounts-db
          image: postgres
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: user
            - name: POSTGRES_DB
              value: accounts
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: accounts-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: accounts-data
          emptyDir: {}