apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: worldoflegion/accounts:0.0.1
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://accounts-db:5434/accounts
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: user
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 700Mi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080