apiVersion: v1
kind: Service
metadata:
  name: accounts-db
spec:
  selector:
    app: accounts-db
  ports:
    - name: postgres
      protocol: TCP
      port: 5434
      targetPort: 5432
  type: ClusterIP